### ISSUE TITLE
[NOT AN ISSUE] A simple question + help request

### ISSUE THREAD

**Issue by EstherMoellman** [da2x/save-data#3]
Hi @da2x !

Firstly, thanks a lot for your Save-Data add-on!

Please @da2x , a have a simple question + help request:

1) Is your Save-Data working only at http? Or is it working also for https and other formats besides http?

2)  I use this autoconfig function: https://github.com/MrOtherGuy/fx-autoconfig
Please, can you help me to adapt your js script for this autoconfig?

Thanks a lot in advance!

**Comment by da2x** [comment]
1. It’s for HTTP and HTTPS. The relevant lines of codes are [this one](https://github.com/da2x/save-data/blob/59af3e1e4080f4871806f2d4ef695d2a6a996bbd/manifest.json#L19) plus [this one](https://github.com/da2x/save-data/blob/59af3e1e4080f4871806f2d4ef695d2a6a996bbd/background.js#L36).
2. No, sorry. The required APIs are only available to extensions, not user scripts.
