### ISSUE TITLE
The extension is no longer compatible with Firefox on Android

### ISSUE THREAD

**Issue by carlosnewmusic** [da2x/save-data#4]
From versión 79.0.5 (Build #2015758619)
https://support.mozilla.org/es/kb/compatibilidad-de-complementos-para-firefox-previe

**Comment by bat999** [comment]
Hi
I use Fennec F-Droid browser with Android.
From here ---> https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/
It has some features from Nightly Firefox... the addons.
But "Save-Data: on" isn't part of the collection.

I have just installed Iceraven-1.15.0 to experiment with...
https://github.com/fork-maintainers/iceraven-browser
It also has some features from Nightly Firefox... the addons.
And "Save-Data: on" IS part of their collection.

And it seems to work!
See the screenshot says **Save-Data: on**

Maybe to make this work with Fennec F-Droid and Nightly Firefox for Android might only need an AMO with a user ID and collection name.

![75data_saver2](https://user-images.githubusercontent.com/640761/156786874-6d53ade5-cf8c-40f8-aac6-e720fb01b054.jpg)
